/**
 * Generates a minimal chain metadata map from viem/chains.
 * This extracts only the data we need (name, nativeCurrency, blockExplorer)
 * reducing bundle size by ~70% compared to importing all chain data.
 */
import { writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import * as allChains from 'viem/chains'

interface ChainMeta {
  name: string
  nativeCurrency: {
    name: string
    symbol: string
    decimals: number
  }
  blockExplorer: string
}

const chainMap: Record<number, ChainMeta> = {}

for (const chain of Object.values(allChains)) {
  if (
    typeof chain === 'object' &&
    chain !== null &&
    'id' in chain &&
    typeof (chain as any).id === 'number'
  ) {
    const c = chain as any
    const blockExplorer = c.blockExplorers?.default?.url
    // Only include chains that have a block explorer and native currency
    if (!blockExplorer || !c.nativeCurrency) continue

    chainMap[c.id] = {
      name: c.name,
      nativeCurrency: c.nativeCurrency,
      blockExplorer,
    }
  }
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const outPath = join(__dirname, '../src/lib/chains.generated.ts')

const output = `// Auto-generated by scripts/generate-chains.ts
// Do not edit manually

export interface ChainMeta {
  name: string
  nativeCurrency: {
    name: string
    symbol: string
    decimals: number
  }
  blockExplorer: string
}

export const chainMap: Record<number, ChainMeta> = ${JSON.stringify(chainMap, null, 2)}
`

writeFileSync(outPath, output)
console.log(`Generated ${Object.keys(chainMap).length} chains to ${outPath}`)
